"""
Compatibility shim for legacy imports
Redirects to PureFieldBrain - the only brain we need
Generated by cleanup script on 2025-08-07 23:12:15
"""

from .pure_field_brain import PureFieldBrain

# Legacy exports that now all map to PureFieldBrain

class UncertaintyMap:
    """Legacy uncertainty tracking - no longer used"""
    def __init__(self, *args, **kwargs):
        self.data = {}
    def update(self, *args, **kwargs):
        pass
